// Ratings are fictional gameplay values based on the creator's descriptions.
// OVR is an authored balance rating, not the arithmetic average of the visible stats.
export const STAT_LABELS={mid:'Средние',three:'Дальние',handle:'Дриблинг',jump:'Прыжок',dunk:'Данки',speed:'Скорость'};
export const PLAYERS=[
 {id:'laika',name:'Лайка',sourceOrder:1,ovr:94,height:'Высокий',scale:1.08,number:1,role:'Универсал',color:'#e6c17a',photo:'assets/portraits/laika.jpg',photoPosition:'50% 28%',stats:{mid:89,three:73,handle:97,jump:96,dunk:98,speed:92,defense:86,pass:90,stamina:94},super:{id:'flight',name:'Взлёт',description:'7 секунд усиленных прыжков и данков. Можно атаковать кольцо с большего расстояния.',duration:7}},
 {id:'kempil',name:'Кемпиль',sourceOrder:2,ovr:90,height:'Высокий',scale:1.07,number:2,role:'Снайпер',color:'#c6d2f4',photo:'assets/portraits/kempil.jpg',photoPosition:'50% 28%',stats:{mid:87,three:96,handle:69,jump:85,dunk:94,speed:79,defense:80,pass:82,stamina:88},super:{id:'sniper',name:'Снайпер',description:'Следующий дальний бросок в течение 7 секунд получает прибавку к точности.',duration:7}},
 {id:'gabar',name:'Габар',sourceOrder:7,ovr:82,height:'Средний',scale:1,number:7,role:'Командный игрок',color:'#aacbb9',photo:'assets/portraits/gabar.jpg',photoPosition:'50% 28%',stats:{mid:82,three:83,handle:81,jump:84,dunk:67,speed:83,defense:82,pass:88,stamina:86},super:{id:'secondwind',name:'Второе дыхание',description:'8 секунд повышенной скорости и перехватов. Выносливость восстанавливается.',duration:8}},
 {id:'demidok',name:'Демидок',sourceOrder:4,ovr:77,height:'Низкий',scale:.92,number:4,role:'Дриблёр',color:'#e9b8a2',photo:'assets/portraits/demidok.jpg',photoPosition:'50% 28%',stats:{mid:68,three:65,handle:94,jump:95,dunk:42,speed:95,defense:68,pass:76,stamina:84},super:{id:'dash',name:'Молния',description:'6 секунд быстрого дриблинга: скорость выше, отобрать мяч сложнее.',duration:6}},
 {id:'aziom',name:'Азиом',sourceOrder:3,ovr:63,height:'Низкий',scale:.91,number:3,role:'Средняя дистанция',color:'#c2b7dd',photo:'assets/portraits/aziom.jpg',photoPosition:'50% 28%',glasses:true,stats:{mid:64,three:61,handle:43,jump:39,dunk:31,speed:59,defense:53,pass:63,stamina:65},super:{id:'focus',name:'Точный момент',description:'Следующий средний бросок в течение 5 секунд получает прибавку к точности.',duration:5}},
 {id:'piniv',name:'Пинив',sourceOrder:6,ovr:54,height:'Высокий',scale:1.065,number:6,role:'Под кольцом',color:'#c4b6a5',photo:'assets/portraits/piniv.jpg',photoPosition:'50% 28%',stats:{mid:39,three:34,handle:36,jump:60,dunk:59,speed:52,defense:49,pass:48,stamina:58},super:{id:'anchor',name:'Крепкая стойка',description:'7 секунд увеличенного радиуса подбора и усиленной защиты под кольцом.',duration:7}}
];
export const REFEREE={id:'askar',name:'Аскар',sourceOrder:5,role:'Судья',height:'Средний',scale:.96,number:0,photo:'assets/portraits/askar.jpg',photoPosition:'50% 28%',referee:true};
export const byId=id=>PLAYERS.find(p=>p.id===id);
